title: blank-template
hero_image: images/banner.png
description: blank-template description
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Step title
